definitions:
  contract.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  contract.RegisterInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  contract.TaskInput:
    properties:
      description:
        type: string
      status:
        type: string
      title:
        type: string
      user_id:
        type: integer
    type: object
  contract.TaskOutput:
    properties:
      created_at:
        type: string
      description:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  contract.UpdateInput:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a Task test.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: User Task
  version: "1.0"
paths:
  /task-test/login:
    post:
      description: Logging in to get jwt token to access admin or user api by roles.
      parameters:
      - description: the body to login a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/contract.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login.
      tags:
      - User
  /task-test/tasks:
    get:
      description: get list task.
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Get List Task.
      tags:
      - Task
    post:
      description: Save User Task.
      parameters:
      - description: the body to create a new Task
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/contract.TaskInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contract.TaskOutput'
      security:
      - task-token: []
      summary: Create Task.
      tags:
      - Task
  /task-test/tasks/{id}:
    delete:
      description: remove a task.
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Delete a Task.
      tags:
      - Task
    get:
      description: get a task.
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Get a Task.
      tags:
      - Task
    put:
      description: Edit User Task.
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      - description: the body to create a new Task
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/contract.TaskInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contract.TaskOutput'
      security:
      - task-token: []
      summary: Update Task.
      tags:
      - Task
  /task-test/users:
    get:
      description: get list user from public access.
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Get List User.
      tags:
      - User
    post:
      description: registering a user from public access.
      parameters:
      - description: the body to register a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/contract.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register a User.
      tags:
      - User
  /task-test/users/{id}:
    delete:
      description: remove a task.
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Delete a User.
      tags:
      - User
    get:
      description: get a user from public access.
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Get  User.
      tags:
      - User
    put:
      description: Edit User User.
      parameters:
      - description: task id
        in: path
        name: id
        required: true
        type: integer
      - description: the body to create a new User
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/contract.UpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - task-token: []
      summary: Update User.
      tags:
      - User
securityDefinitions:
  task-token:
    description: 'Value is: "Bearer {access_token}", where access_token is retrieved
      from cms-service/v1/login'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
